name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - anaconda-anon-usage=0.7.4=pyhb46e38b_100
  - archspec=0.2.5=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=openblas
  - boltons=25.0.0=py312h06a4308_0
  - bottleneck=1.4.2=py312haa0f9ac_1
  - brotlicffi=1.1.0.0=py312hbdd6827_0
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py312h06a4308_0
  - cffi=2.0.0=py312h4eded50_1
  - charset-normalizer=3.4.4=py312h06a4308_0
  - conda=25.9.1=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py312h06a4308_1
  - conda-package-streaming=0.12.0=py312h06a4308_1
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=46.0.3=py312h0a354b3_0
  - curl=8.16.0=he2463ab_0
  - distro=1.9.0=py312h06a4308_0
  - expat=2.7.3=h3385a95_0
  - fmt=11.2.0=hca5f364_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozendict=2.4.6=py312hee96239_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gettext=0.21.0=hedfda30_2
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_2
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py312h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - jpeg=9f=h5ce9db8_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=3.0.0=py312h06a4308_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libmamba=2.3.2=h4368100_0
  - libmambapy=2.3.2=py312hea2f153_0
  - libnghttp2=1.67.1=h697f920_0
  - libopenblas=0.3.30=h46f56fc_2
  - libpng=1.6.50=h2ed474d_0
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - menuinst=2.4.1=py312h06a4308_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py312hacdc0fc_0
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - numexpr=2.14.1=py312ha5a4a6c_0
  - numpy=2.3.4=py312h816806e_1
  - numpy-base=2.3.4=py312h7203c5b_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py312h06a4308_1
  - pandas=2.3.3=py312h23c847b_1
  - pango=1.50.7=h668f713_2
  - pcre2=10.42=hebb0a14_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_2
  - pycparser=2.23=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_1
  - python=3.12.4=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312h06a4308_0
  - r=4.3.1=r43_0
  - r-base=4.3.1=h8399a1e_1
  - r-boot=1.3_28.1=r43h6115d3f_0
  - r-class=7.3_22=r43h76d94ec_0
  - r-cluster=2.1.4=r43h640688f_0
  - r-codetools=0.2_19=r43h6115d3f_0
  - r-foreign=0.8_85=r43h76d94ec_0
  - r-kernsmooth=2.23_22=r43h640688f_0
  - r-lattice=0.22_5=r43h76d94ec_0
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_1.1=r43h76d94ec_0
  - r-mgcv=1.9_0=r43h76d94ec_0
  - r-nlme=3.1_163=r43h640688f_0
  - r-nnet=7.3_19=r43h76d94ec_0
  - r-recommended=4.3.1=r43_0
  - r-rpart=4.1.21=r43h76d94ec_0
  - r-spatial=7.3_17=r43h76d94ec_0
  - r-survival=3.5_7=r43h76d94ec_0
  - readline=8.3=hc2a1206_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py312h06a4308_1
  - ruamel.yaml=0.18.16=py312h4aee224_0
  - ruamel.yaml.clib=0.2.14=py312h4aee224_0
  - scipy=1.16.3=py312he2bc341_0
  - setuptools=80.9.0=py312h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.28=h3108a97_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tktable=2.10=hfce700a_2
  - tqdm=4.67.1=py312h7040dfc_1
  - truststore=0.10.1=py312h06a4308_1
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=hd233ad5_2
  - zstandard=0.23.0=py312h2c38b39_1
  - zstd=1.5.6=hc292b87_0
prefix: /usr/wipp/conda/24.5.0
